import assert from "node:assert/strict";
import test from "node:test";
import { createCleanDemoState } from "../src/data/demo-state.ts";
import { cancelPurchaseRequest, emptyPurchaseRequest, evaluatePurchaseRequest, formFromApproval, purchaseSamples, savePurchaseRequest, validatePurchaseRequest } from "../src/lib/approvals/purchase-requests.ts";
import { approveMultisig } from "../src/lib/multisig/types.ts";

const form = (values = {}) => ({ ...emptyPurchaseRequest(), ...purchaseSamples["Travel approval"], ...values });

test("creates and saves a request draft", () => { const state=savePurchaseRequest(createCleanDemoState(),form(),undefined,false);assert.equal(state.approvals[0].requestStatus,"Draft");assert.equal(state.dashboard.pendingCount,3);assert.equal(state.dashboard.activity[0].category,"Request created"); });
test("edits a draft without creating a duplicate request", () => { const created=savePurchaseRequest(createCleanDemoState(),form(),undefined,false);const edited=savePurchaseRequest(created,{...formFromApproval(created.approvals[0]),amount:"720"},created.approvals[0].id,false);assert.equal(edited.approvals.length,created.approvals.length);assert.equal(edited.approvals[0].amount,720); });
test("submits and classifies standard approval", () => { const state=savePurchaseRequest(createCleanDemoState(),form(),undefined,true);assert.equal(state.approvals[0].approvalType,"Standard");assert.equal(state.approvals[0].requestStatus,"Pending");assert.equal(state.dashboard.pendingCount,4); });
test("classifies matching requests below £300 as auto-approved", () => { const evaluation=evaluatePurchaseRequest(form(purchaseSamples["Standard software purchase"]),createCleanDemoState().rules.seededRules);assert.equal(evaluation.approvalType,"Auto-approved"); });
test("classifies requests above £1,000 as treasury multisig", () => { const state=savePurchaseRequest(createCleanDemoState(),form(purchaseSamples["Multisig treasury payment"]),undefined,true);assert.equal(state.approvals[0].approvalType,"Treasury multisig");assert.equal(state.treasury.requests[0].decisions.length,0); });
test("accepts valid requester emails from any domain", () => { for (const requesterEmail of ["johnfletcher@gmail.com","john@northstar.io","user@outlook.com","person@company.co.uk"]) assert.doesNotThrow(()=>validatePurchaseRequest(form({requesterEmail}))); });
test("rejects invalid or blank requester emails", () => { assert.throws(()=>validatePurchaseRequest(form({amount:"0"})),/positive/);for (const requesterEmail of ["invalid-email","@gmail.com"]) assert.throws(()=>validatePurchaseRequest(form({requesterEmail})),/valid requester email/);assert.throws(()=>validatePurchaseRequest(form({requesterEmail:"  "})),/required/); });
test("re-evaluates approval type after an edit", () => { const state=savePurchaseRequest(createCleanDemoState(),form(),undefined,true);const edited=savePurchaseRequest(state,{...formFromApproval(state.approvals[0]),amount:"1480"},state.approvals[0].id,true);assert.equal(edited.approvals[0].approvalType,"Treasury multisig"); });
test("role switching preserves requests and duplicate signers are rejected", () => { const state=savePurchaseRequest(createCleanDemoState(),form(purchaseSamples["Multisig treasury payment"]),undefined,true);const request=state.treasury.requests[0];const first=approveMultisig(request,"SIGNER-AMANDA",true,new Date("2026-07-21"));assert.throws(()=>approveMultisig(first,"SIGNER-AMANDA",true,new Date("2026-07-21")),/already decided/);const switched={...state,treasury:{...state.treasury,currentSignerId:"SIGNER-OLIVIA"}};assert.equal(switched.treasury.requests[0].id,request.id); });
test("cancelling requests remains idempotent", () => { const created=savePurchaseRequest(createCleanDemoState(),form(),undefined,true);const id=created.approvals[0].id;const cancelled=cancelPurchaseRequest(created,id);const twice=cancelPurchaseRequest(cancelled,id);assert.equal(twice.dashboard.activity.filter(item=>item.eventId===`${id}:cancelled`).length,1); });
test("reset restores identity and treasury demo forms", () => { const clean=createCleanDemoState();assert.equal(clean.treasury.currentSignerId,"SIGNER-AMANDA");assert.deepEqual(clean.treasury.bridgeDemo,{amount:"0.01",destination:"",status:"idle"});assert.deepEqual(clean.treasury.swapDemo,{fromAsset:"EURC",toAsset:"USDC",amount:"10",status:"idle"}); });
